name: ai-gateway

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100mb"
    max-file: "3" # Rotate after 3 files of 100mb or similar, effectively handling rotation

include:
  - path: services/data/compose.yml
  - path: services/gateway/compose.yml
  - path: services/observability/compose.yml
  - path: services/identity/compose.yml

networks:
  ai-gateway-connect:
    name: ai-gateway-connect
    driver: bridge
